name: Publish @next

on:
    workflow_dispatch:
    schedule:
        - cron: "0 7 * * *"

jobs:
    check:
        if: github.repository == 'paradoxuum/commander' && github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        outputs:
            version: ${{ env.VERSION }}
            version_changed: ${{ env.VERSION_CHANGED }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set version
              run: |
                  CURRENT=$(cat package.json | jq -r .version)
                  echo "VERSION="${CURRENT::-1}$((${CURRENT: -1} + 1))"-dev.$(git rev-parse --short HEAD)" >> $GITHUB_ENV

            - name: Check version
              run: |
                  LATEST_VERSION=$(npm view @rbxts/commander dist-tags.next)
                  echo "VERSION_CHANGED=$(test ${{ env.VERSION }} != $LATEST_VERSION && echo true || echo false)" >> $GITHUB_ENV

    publish:
        runs-on: ubuntu-latest
        needs: check
        if: needs.check.outputs.version_changed == 'true'
        env:
            VERSION: ${{ needs.check.outputs.version }}
        permissions:
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 9

            - uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"
                  cache: pnpm
                  cache-dependency-path: ./pnpm-lock.yaml

            - name: Set version
              run: pnpm version --no-git-tag-version ${{ env.VERSION }}

            - name: Publish @next
              run: pnpm publish --tag next
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
